/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CampainNotes;


public class App {
    public String getGreeting() {
        return "My Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        CampainManager creator = new CampainManager();
        if (creator.checkDatabasesAvailability()){
            System.out.println("Databases available.");
        }else {
            System.out.println("Databases not available.");
        }
    }
}
