/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CampaignNotes;


import CampaignNotes.tracking.otel.OpenTelemetryConfig;
public class App {

    public static void main(String[] args) {
        // Initialize OpenTelemetry for tracing
        OpenTelemetryConfig.initialize();
        

        // Start Terminal Interface
        TerminalInterface terminalInterface = new TerminalInterface();
        terminalInterface.start();

    }
}
