/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CampaignNotes;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

@DisplayName("Application Tests")
class AppTest {
    
    @Test
    @DisplayName("Application should have a greeting message")
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
